{ pkgs, ... }:

let
  nixosPackage = import ../common/scripts/bin.nix { inherit pkgs; };
in
{
  environment.systemPackages = [
    nixosPackage.nixosWrapper
    pkgs.bashInteractive
    pkgs.bat
    pkgs.btrfs-progs
    pkgs.bzip2
    pkgs.clamav
    pkgs.coreutils-full
    pkgs.cryptsetup
    pkgs.curl
    pkgs.ddrescue
    pkgs.dhcpcd
    pkgs.diffutils
    pkgs.disko
    pkgs.dnsutils
    pkgs.dosfstools
    pkgs.e2fsprogs
    pkgs.efibootmgr
    pkgs.ethtool
    pkgs.exfatprogs
    pkgs.f2fs-tools
    pkgs.fastfetch
    pkgs.fd
    pkgs.file
    pkgs.findutils
    pkgs.fwupd
    pkgs.gawk
    pkgs.git
    pkgs.gnugrep
    pkgs.gnupg
    pkgs.gzip
    pkgs.hdparm
    pkgs.htop
    pkgs.inxi
    pkgs.iotop
    pkgs.iproute2
    pkgs.iputils
    pkgs.less
    pkgs.logrotate
    pkgs.lshw
    pkgs.lsof
    pkgs.ltrace
    pkgs.lvm2
    pkgs.mtools
    pkgs.mc
    pkgs.mdadm
    pkgs.micro
    pkgs.mtr
    pkgs.nano
    pkgs.ncdu
    pkgs.net-tools
    pkgs.nilfs-utils
    pkgs.nmap
    pkgs.nmon
    pkgs.nvme-cli
    pkgs.openvpn
    pkgs.openssh
    pkgs.openssl
    pkgs.parted
    pkgs.pciutils
    pkgs.progress
    pkgs.ripgrep
    pkgs.rsync
    pkgs.samba
    pkgs.screen
    pkgs.sg3_utils
    pkgs.smartmontools
    pkgs.socat
    pkgs.sops
    pkgs.strace
    pkgs.sysstat
    pkgs.testdisk
    pkgs.tmux
    pkgs.traceroute
    pkgs.tree
    pkgs.unzip
    pkgs.usbutils
    pkgs.util-linux
    pkgs.vim
    pkgs.wget
    pkgs.which
    pkgs.wireguard-tools
    pkgs.wipe
    pkgs.xfsprogs
    pkgs.xz
    pkgs.zip
    pkgs.zfs
    pkgs.jq
    pkgs.yq
  ]
  ++ import ./bootstrapPackages.nix { inherit pkgs; };
}
