#!/usr/bin/env bash

set -euo pipefail

DIR="$__NIXOS_DIR"
ROLE="$__NIXOS_ROLE"

VARS_DIR="$DIR/vars"
VARS="$VARS_DIR/vars.nix"

SECRETS="$VARS_DIR/secrets.yaml"

case "$ROLE" in
  laptop)
    SOPS_DIR="/persist/sops-nix"
    ;;
  server)
    SOPS_DIR="/var/lib/sops-nix"
    ;;
  *)
    echo "Error: unexpected role '$ROLE'" >&2
    exit 1
    ;;
esac

case "$1" in
    vars)
        "$EDITOR" "$VARS"
        ;;
    sops)
        sudo GNUPGHOME="$SOPS_DIR" sops "$SECRETS"
        ;;
    *)
    echo "Error: expected argument (vars/sops)" >&2
        exit 1
        ;;
esac
