#!/usr/bin/env bash

# NIXOS_ROLE is the configuration role
if [ -z "$NIXOS_ROLE" ]; then
    echo "Error: NIXOS_ROLE is not set." >&2
    exit 1
fi

# allowed roles: laptop, server
if ! [[ "$NIXOS_ROLE" =~ ^(server|laptop)$ ]]; then
  echo "Error: unexpected role $NIXOS_ROLE" >&2
  exit 1
fi

ROLE="$NIXOS_ROLE"

# NIXOS_ROOT_MOUNT is used for bootstrapping
# this flake to another machine
if [ -z "$NIXOS_ROOT_MOUNT" ]; then
    NIXOS_ROOT_MOUNT=""
fi

# NIXOS_DIR is the flake directory
if [ -z "$NIXOS_DIR" ]; then
    echo "Error: NIXOS_DIR is not set." >&2
    exit 1
fi

DIR="$NIXOS_ROOT_MOUNT$NIXOS_DIR"

# NIXOS_SCRIPTS is the directory
# to look for scripts in
if [ -z "$NIXOS_SCRIPTS" ]; then
    SCRIPTS="$DIR/cli"
else
    SCRIPTS="$NIXOS_SCRIPTS"
fi

# the rest of the script can use
# $ROLE, $DIR and $SCRIPTS

# print directory tree when run with no arguments
if [ $# -eq 0 ]; then
    cmd=("tree" "--filesfirst")

# run scripts
elif [ -f "$SCRIPTS/$1" ]; then
	cmd=("$SCRIPTS/$1" "${@:2}")

# run commands
else
	cmd=("$@")
fi

(
    # subshell into $DIR
    # unless bootstrap
    if [ "$1" != "bootstrap" ]; then
       cd "$DIR" || exit 1
    fi

    # define context
    export __NIXOS_ROLE=$ROLE
    export __NIXOS_DIR=$DIR
    export __NIXOS_SCRIPTS=$SCRIPTS

    # additional context for init script
    export __NIXOS_INIT_ROOT_MOUNT=$NIXOS_ROOT_MOUNT
    export __NIXOS_INIT_DIR=$NIXOS_DIR

    # run required command
    "${cmd[@]}"
)
