#!/usr/bin/env bash

set -euo pipefail

# globals to be used here and by other scripts
FLAKE="/persist/nixos"
IMPERMANENCE="/persist/root"
SOPS="/persist/sops-nix"

# NIXOS_ROLE is the configuration role
if [ -z "${NIXOS_ROLE:-}" ]; then
    echo "Error: NIXOS_ROLE is not set." >&2
    exit 1
fi

# allowed roles: workstation, server, pi
if ! [[ "${NIXOS_ROLE:-}" =~ ^(workstation|server|pi)$ ]]; then
  echo "Error: unexpected role $NIXOS_ROLE" >&2
  exit 1
fi

ROLE="$NIXOS_ROLE"

# NIXOS_MOUNT is used for bootstrapping
# this flake to another machine
if [ -z "${NIXOS_MOUNT:-}" ]; then
    NIXOS_MOUNT=""
fi

MOUNT="$NIXOS_MOUNT"

# NIXOS_SCRIPTS is the directory
# to look for scripts in
if [ -z "${NIXOS_SCRIPTS:-}" ]; then
    NIXOS_SCRIPTS="$MOUNT/$FLAKE/cli/scripts"
fi

SCRIPTS="$NIXOS_SCRIPTS"

# NIXOS_NONFLAKE is whether to
# use flakes or not
if [ -z "${NIXOS_NONFLAKE:-}" ]; then
    NIXOS_NONFLAKE="0"
fi

NONFLAKE="$NIXOS_NONFLAKE"

# the rest of the script can use
# $ROLE, $MOUNT, $SCRIPTS, $NONFLAKE,
# $FLAKE, $IMPERMANENCE and $SOPS

# CASE 1: print directory tree when run with no arguments
if [ $# -eq 0 ]; then
    cmd=("tree" "--filesfirst")

# CASE 2: run commands
elif [ -f "$SCRIPTS/${1:-}" ]; then
	cmd=("$SCRIPTS/${1:-}" "${@:2}")

# CASE 3: dispatch to flake
else
	cmd=("$@")
fi

(
    # subshell into $FLAKE
    # unless bootstrap
    if [ "${1:-}" != "bootstrap" ]; then
       cd "$MOUNT$FLAKE" || exit 1
    fi

    # define context
    export __NIXOS_ROLE=$ROLE
    export __NIXOS_MOUNT=$MOUNT
    export __NIXOS_SCRIPTS=$SCRIPTS
    export __NIXOS_NONFLAKE=$NONFLAKE

    # define globals
    export __NIXOS_GLOBALS_FLAKE=$FLAKE
    export __NIXOS_GLOBALS_SOPS=$SOPS
    export __NIXOS_GLOBALS_IMPERMANENCE=$IMPERMANENCE

    # run required command
    "${cmd[@]}"
)
