#!/usr/bin/env bash

set -euo pipefail

find "$__NIXOS_DIR" -path "$__NIXOS_DIR/.git" -prune -o -exec chown "$USER": {} +

find "$__NIXOS_DIR" -path "$__NIXOS_DIR/.git" -prune -o -type d -exec chmod 700 {} \;
find "$__NIXOS_DIR" -path "$__NIXOS_DIR/.git" -prune -o -type f -exec chmod 600 {} \;

chmod 700 -R "$__NIXOS_DIR/cli"
