#!/usr/bin/env bash

set -euo pipefail

# required for bootstrapping from
# existing machines that use umask 0077
umask 0022

# ask for sudo upfront
if ! sudo -v; then
    echo "Error: sudo authentication failed" >&2
    exit 1
fi

# keep sudo alive while script runs
(
    while true; do
        sudo -n true
        sleep 60
        kill -0 "$$" || exit
    done
) 2>/dev/null &

# commandline args
VERB="${1:-}"
ARG1="${2:-}"
ARG2="${3:-}"

# basic environment
ROLE="$__NIXOS_ROLE"
MOUNT="$__NIXOS_MOUNT"
DIR="$MOUNT$__NIXOS_GLOBALS_FLAKE"
ARCH="$(nix eval --impure --raw --expr builtins.currentSystem)"
NONFLAKE="$__NIXOS_NONFLAKE"

# for variables
VARS_DIR="$DIR/vars"
VARS="$VARS_DIR/vars.nix"

# for secrets
SOPS_YAML="$DIR/.sops.yaml"
SECRETS="$VARS_DIR/secrets.yaml"
TEMP_SECRETS="/tmp/sops-nix-init.yaml"
SOPS_DIR="$MOUNT$__NIXOS_GLOBALS_SOPS"

# for impermanence: post-install
REAL_ROOT=""
REAL_HOME="/home/$USER"
PERSIST_DIR_ROOT="$MOUNT$__NIXOS_GLOBALS_IMPERMANENCE"
PERSIST_DIR_HOME="$MOUNT$__NIXOS_GLOBALS_IMPERMANENCE/home/$USER"

########
# DISKS
######## workstation, server

if [ "$VERB" == "disks" ]; then

    # allowed roles: workstation, server
    if ! [[ "${ROLE:-}" =~ ^(workstation|server)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi

    : "${ARG1:?Error: expected argument (boot/swap/root/mount)}"

    : "${BOOT:?Error: BOOT is not set (e.g. /dev/disk/by-partuuid/xxx)}"
    echo "BOOT=$BOOT"
    : "${SWAP:?Error: SWAP is not set (e.g. /dev/disk/by-partuuid/xxx)}"
    echo "SWAP=$SWAP"
    : "${ROOT:?Error: ROOT is not set (e.g. /dev/disk/by-partuuid/xxx)}"
    echo "ROOT=$ROOT"

    if ! [ -b "$BOOT" ]; then
        echo "Error: $BOOT is not a block device"
        exit 1
    fi

    if ! [ -b "$SWAP" ]; then
        echo "Error: $SWAP is not a block device"
        exit 1
    fi

    if ! [ -b "$ROOT" ]; then
        echo "Error: $ROOT is not a block device"
        exit 1
    fi

    APPLY=$ARG2
    if [ "$APPLY" != "apply" ]; then
      echo "DRY RUN: no destructive actions will be performed. Re-run with 'apply' at the end of command to actually apply."
    fi

    read -rp "Are you absolutely sure you want to proceed? Type 'I UNDERSTAND' to continue: " CONFIRM
    if [[ "$CONFIRM" != "I UNDERSTAND" ]]; then
      echo "Aborting."
      exit 1
    fi

    # helper for running or echoing
    run() {
      echo "+ $*"
      if [ "$APPLY" == "apply" ]; then
          "$@"
      fi
    }

    # wait for udev
    run sudo udevadm settle

    if [ "$ARG1" == "boot" ]; then

        # 1) format boot as FAT32 (ESP)
        run sudo mkfs.vfat -F 32 -n BOOT "$BOOT"

    elif [ "$ARG1" == "swap" ]; then

        # 2) setup swap
        run sudo mkswap "$SWAP"
        run sudo swapon "$SWAP"

    elif [ "$ARG1" == "root" ]; then

        # 3) wipe signatures on root before LUKS to avoid troubles
        run sudo wipefs -a "$ROOT" || true

        # 4) LUKS encrypt root
        # - use LUKS2, pbkdf=argon2id defaults; prompts for passphrase
        run sudo cryptsetup luksFormat --type luks2 "$ROOT"
        run sudo cryptsetup luksOpen "$ROOT" root

        # 5) wait for /dev/mapper/root
        run udevadm settle

        # 6) create ZFS pool on /dev/mapper/root
        # if re-using disk, consider "zpool destroy -f rpool" first (user responsibility)
        ZPOOL_NAME="rpool"
        ZPOOL_DEVICE="/dev/mapper/root"

        # recommended zpool create options from docs
        ZPOOL_ARGS=(
          -O compression=lz4
          -O xattr=sa
          -O acltype=posixacl
          -O atime=off
          -O mountpoint=none
          -o ashift=12
        )

        # create pool
        run sudo zpool create "$ZPOOL_NAME" "${ZPOOL_ARGS[@]}" "$ZPOOL_DEVICE"

        # 7) create datasets
        run sudo zfs create rpool/nixos
        run sudo zfs create rpool/nixos/root -o mountpoint=legacy
        run sudo zfs create rpool/nixos/nix -o mountpoint=legacy
        run sudo zfs create rpool/nixos/persist -o mountpoint=legacy

        # 8) empty snapshots for impermanence
        run sudo zfs snapshot rpool/nixos/root@blank

    elif [ "$ARG1" == "mount" ]; then

        # 10) mount filesystems
        run sudo mkdir -p /mnt
        run sudo mount -t zfs rpool/nixos/root /mnt
        run sudo mkdir -p /mnt/nix /mnt/persist
        run sudo mount -t zfs rpool/nixos/nix /mnt/nix
        run sudo mount -t zfs rpool/nixos/persist /mnt/persist

        # 11) mount boot
        run sudo mkdir -p /mnt/boot
        run sudo mount "$BOOT" /mnt/boot

    fi

    echo "Done."

########
# CLONE
######## workstation, server, pi

elif [ "$VERB" == "clone" ]; then

    # allowed roles: workstation, server, pi
    if ! [[ "${ROLE:-}" =~ ^(workstation|server|pi)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi

    sudo mkdir -p "$DIR"
    sudo chown "$USER:" "$DIR"
    git clone https://github.com/sotormd/nixos "$DIR" --depth=1

#######
# VARS
####### workstation, server, pi

elif [ "$VERB" == "vars" ]; then

    # allowed roles: workstation, server, pi
    if ! [[ "${ROLE:-}" =~ ^(workstation|server|pi)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi

    MACHINE_ID="$(tr -d '\n' < /etc/machine-id)"
    HOST_ID="${MACHINE_ID:0:8}"

    mkdir -p "$VARS_DIR"

    if [ -f "$VARS" ] && [[ "$ARG1" != "replace" ]]; then
        echo "Error: vars.nix already exists" >&2
        exit 1
    fi

    if [[ "${ROLE:-}" =~ ^(workstation)$ ]]; then

        BOOT=${BOOT:-}
        SWAP=${SWAP:-}
        ROOT=${ROOT:-}

        # create vars file
        cat > "$VARS" <<EOF
# variables are used to capture differences in hosts using the same role

# this file was automatically generated during bootstrap
# use this file to store variables consumed by the flake

# note that variables end up in the world-readable nix store
# use sops-nix secrets for sensitive information

# before rebuilding, ensure that all variables are properly defined
# invalid / inaccurate variables can lead to a broken system
# bootstrap DOES NOT POPULATE VARIABLES with sane values, only examples

# the following values have been populated from the installation environment
# - device.machineId
# - device.hostId
# - partitions.boot
# - partitions.swap
# - partitions.root

{

  # device variables
  device = {

    # hostname in /etc/hostname
    hostName = "example";

    # machine id in /etc/machine-id
    # required by systemd for consistent logs
    # passed as a boot parameter
    machineId = "$MACHINE_ID";

    # host id
    # required by ZFS
    hostId = "$HOST_ID";

  };

  # partition PARTUUIDS
  # get these from /dev/disk/by-partuuid/...
  partitions = {

    # FAT32 boot partition
    boot = "${BOOT##*/}";

    # swap partition
    swap = "${SWAP##*/}";

    # LUKS partition with rpool
    root = "${ROOT##*/}";

  };

  # additional filesystem mounts
  filesystem = {

    # configure luks encrypted devices
    # each entry should have a uuid and keyfile
    luks = { };

    # configure mounts
    # directly map to fileSystems.* blocks
    mount = {

      # raw mounts, no additional options
      raw = { };

      # nosuid, nodev
      harden = { };

      # nosuid, nodev, noexec
      data = { };

      # nosuid, nodev, ro
      immutable = { };

      # nosuid, nodev, noexec, ro
      static = { };

    };

  };

  # usbguard allowed devices
  # all others are blocked
  usbs = [ ];

  # user information
  user = {

    # nsswitch username in /etc/passwd
    name = "example";

    # git configuration
    git = {

      # name used for git commits
      name = "example";

      # email used for git commits
      email = "example@example";

      # signing key used for git commits
      signing-key = "/home/example/.ssh/id_ed25519_example_git_sign.pub";

      # allowed signers file
      allowed-signers = "/home/example/.ssh/git_allowed_signers";

    };

    # ssh host aliases
    # each with a user, host, port and keyfile
    sshAliases = { };

  };

  # localization and internationalization
  localization = {

    # Continent/City timezone
    timeZone = "UTC";

    # keyboard layout
    keyboard = "us";

    # locale
    locale = "en_US.UTF-8";

  };

  # networking options
  network = {

    # primary DNS resolver
    resolver = "10.0.0.3";

    # wpa_supplicant wireless networking
    wireless = {

      # enable wireless networking
      enable = false;

      # wireless NIC identifier
      interface = "wlp1s0";

      # wireless network ssid
      # WPA3-SAE password is stored using sops-nix
      ssid = "example";

      # wireless network gateway
      gateway = "10.0.0.1";

      # static IP address
      address = "10.0.0.2";

    };

    # wireguard vpn
    wireguard = {

      # enable wireguard
      enable = false;

      # wireguard address
      address = "10.20.0.2";

      # wireguard port
      port = 51820;

      # wireguard peers
      peers = [ ];

    };

    # hostapd AP and authentication server
    hostapd = {

      # enable hostapd
      enable = false;

      # hostapd wireless NIC identifier
      # hostapd and wireless can't use the same interface
      interface = "wlp1s1";

      # uplink interface
      # provides connectivity
      uplink = "eth0";

      # regulatory domain
      # as a country codeDNScrypt
      domain = "US";

      # ssid name
      # WPA3-SAE password is stored using sops-nix
      ssid = "example-lan";

      # address for gateway
      # prefix 24 will be used
      address = "192.168.0.1";

    };

    # optional wired networking
    # with DHCP
    wired = {

      # enable wired networking
      enable = false;

      # wired NIC identifier
      interface = "eth0";

    };

  };

  # displays
  displays = {

    # outputs
    # each with an identifier, resolution, refresh and position
    # as used in sway configuration
    outputs = {
      laptop = {
        identifier = "eDP-1";
        resolution = "1920x1200";
        refresh = "60Hz";
        position = "0 0";
      };
      monitor = {
        identifier = "HDMI-A-1";
        resolution = "1920x1080";
        refresh = "60Hz";
        position = "1920 0";
      };
    };

    # primary output
    primary = "monitor";

  };

  # additional feature toggles
  features = {

    # secureboot with lanzaboote
    secureboot.enable = false;

    # impermanence with ZFS and bind mounts
    impermanence.enable = false;

  };

  # specialisation modes
  modes = {

    # roaming mode
    # for use outside home
    roaming.enable = false;

    # gnome mode
    # gnome dekstop
    gnome.enable = false;

  };

  # use selfhosted features
  selfhosted = {

    # searxng metasearch engine
    # used for web searches
    # domain is a duckdns domain
    searxng = {
      enable = false;
      domain = "example.duckdns.org";
    };

    # vaultwarden password manager
    # used for web vault
    # domain is a duckdns domain
    vaultwarden = {
      enable = false;
      domain = "example.duckdns.org";
    };

    # i2pd router
    # used for webconsole and HTTP proxy
    # address is a private address
    # domain is a duckdns domain
    i2pd = {
      enable = false;
      address = "10.0.0.3";
      domain = "example.duckdns.org";
    };

    # qBittorrent bittorrent client
    # used for webui
    # domain is a duckdns domain
    qbt = {
      enable = false;
      domain = "example.duckdns.org";
    };

  };

  # service toggles
  services = {

    # dnscrypt-proxy DoH
    # loopback service
    dnscrypt = {
      enable = true;
    };

    # ssh server
    # lan service
    #
    # port is a port
    # trusted-keys is a list of ed25519 ssh public keys
    # allow is a private CIDR (LAN)
    ssh = {
      enable = false;
      port = 2222;
      trusted-keys = [ ];
      allow = "10.0.0.4/32";
    };

  };

  # seed this machine remotely
  # trusted-keys is a list of nix public keys
  seed = {
    enable = false;
    trusted-keys = [ ];
  };

}
EOF

        echo 'before rebuilding, ensure that all variables are properly defined
invalid / inaccurate variables can lead to a broken system
bootstrap DOES NOT POPULATE VARIABLES with sane values, only examples

the following values have been populated from the installation environment
- device.machineId
- device.hostId
- partitions.boot
- partitions.swap
- partitions.root'

    elif [[ "${ROLE:-}" =~ ^(server)$ ]]; then

        BOOT=${BOOT:-}
        SWAP=${SWAP:-}
        ROOT=${ROOT:-}

        # create vars file
        cat > "$VARS" <<EOF
# variables are used to capture differences in hosts using the same role

# this file was automatically generated during bootstrap
# use this file to store variables consumed by the flake

# note that variables end up in the world-readable nix store
# use sops-nix secrets for sensitive information

# before rebuilding, ensure that all variables are properly defined
# invalid / inaccurate variables can lead to a broken system
# bootstrap DOES NOT POPULATE VARIABLES with sane values, only examples

# the following values have been populated from the installation environment
# - device.machineId
# - device.hostId
# - partitions.boot
# - partitions.swap
# - partitions.root

{

  # device variables
  device = {

    # hostname in /etc/hostname
    hostName = "example";

    # machine id in /etc/machine-id
    # required by systemd for consistent logs
    # passed as a boot parameter
    machineId = "$MACHINE_ID";

    # host id
    # required by ZFS
    hostId = "$HOST_ID";

  };

  # partition PARTUUIDS
  # get these from /dev/disk/by-partuuid/...
  partitions = {

    # FAT32 boot partition
    boot = "${BOOT##*/}";

    # swap partition
    swap = "${SWAP##*/}";

    # LUKS partition with rpool
    root = "${ROOT##*/}";

  };

  # additional filesystem mounts
  filesystem = {

    # configure luks encrypted devices
    # each entry should have a uuid and keyfile
    luks = { };

    # configure mounts
    # directly map to fileSystems.* blocks
    mount = {

      # raw mounts, no additional options
      raw = { };

      # nosuid, nodev
      harden = { };

      # nosuid, nodev, noexec
      data = { };

      # nosuid, nodev, ro
      immutable = { };

      # nosuid, nodev, noexec, ro
      static = { };

    };

  };

  # usbguard allowed devices
  # all others are blocked
  usbs = [ ];

  # user information
  user = {

    # nsswitch username in /etc/passwd
    name = "example";

  };

  # localization and internationalization
  localization = {

    # Continent/City timezone
    timeZone = "UTC";

    # keyboard layout
    keyboard = "us";

    # locale
    locale = "en_US.UTF-8";

  };

  # networking options
  network = {

    # primary DNS resolver
    resolver = "127.0.0.1";

    # wpa_supplicant wireless networking
    wireless = {

      # wireless NIC identifier
      interface = "wlp1s0";

      # wireless network ssid
      ssid = "example";

      # wireless network gateway
      gateway = "10.0.0.1";

      # static IP address
      address = "10.0.0.2";

    };

    # wireguard vpn
    wireguard = {

      # wireguard address
      address = "10.20.0.2";

      # wireguard port
      port = 51820;

      # wireguard peers
      peers = [ ];

    };

  };

  # additional feature toggles
  features = {

    # secureboot with lanzaboote
    secureboot.enable = false;

    # impermanence with ZFS and bind mounts
    impermanence.enable = false;

  };

  # service toggles
  services = {

    # dnscrypt-proxy DoH
    # loopback service
    dnscrypt = {
      enable = true;
    };

    # ssh server
    # lan service
    #
    # port is a port
    # trusted-keys is a list of ed25519 ssh public keys
    # allow is a private CIDR (LAN)
    ssh = {
      enable = false;
      port = 2222;
      trusted-keys = [ ];
      allow = "10.0.0.4/32";
    };

    # nginx web server
    # svcvm service
    #
    # staging is to use Let's Encrypt staging
    # email is address used for acme
    # domain is a duckdns domain
    # allow is a private CIDR (wireguard)
    # debug is whether to allow debugging
    nginx = {
      enable = false;
      staging = false;
      email = "example@example";
      domain = "example.duckdns.org";
      allow = "10.20.0.2/32";
      debug = true;
    };

    # searxng metasearch engine
    # svcvm service
    #
    # allow is a private CIDR (wireguard)
    # debug is whether to allow debugging
    searxng = {
      enable = false;
      allow = "10.20.0.2/32";
      debug = true;
    };

    # vaultwarden password manager
    # svcvm service
    #
    # signups is whether to allow new signups
    # allow is a private CIDR (wireguard)
    # debug is whether to allow debugging
    vaultwarden = {
      enable = false;
      signups = false;
      allow = "10.20.0.2/32";
      debug = true;
    };

    # i2pd router
    # svcvm service
    #
    # allow is a private CIDR (wireguard)
    # debug is whether to allow debugging
    i2pd = {
      enable = false;
      allow = "10.20.0.2/32";
      debug = true;
    };

    # qbittorrent bittorrent client
    # svcvm service
    #
    # allow is a private CIDR (wireguard)
    # debug is whether to allow debugging
    qbt = {
      enable = false;
      allow = "10.20.0.2/32";
      debug = true;
    };

  };

  # seed this machine remotely
  # trusted-keys is a list of nix public keys
  seed = {
    enable = false;
    trusted-keys = [ ];
  };

}
EOF

        echo 'before rebuilding, ensure that all variables are properly defined
invalid / inaccurate variables can lead to a broken system
bootstrap DOES NOT POPULATE VARIABLES with sane values, only examples

the following values have been populated from the installation environment
- device.machineId
- device.hostId
- partitions.boot
- partitions.swap
- partitions.root'


    elif [[ "${ROLE:-}" =~ ^(pi)$ ]]; then

        # create vars file
        cat > "$VARS" <<EOF
# variables are used to capture differences in hosts using the same role

# this file was automatically generated during bootstrap
# use this file to store variables consumed by the flake

# note that variables end up in the world-readable nix store
# use sops-nix secrets for sensitive information

# before rebuilding, ensure that all variables are properly defined
# invalid / inaccurate variables can lead to a broken system
# bootstrap DOES NOT POPULATE VARIABLES with sane values, only examples

# the following values have been populated from the installation environment
# - device.machineId
# - device.hostId

{
  # device variables
  device = {

    # hostname in /etc/hostname
    hostName = "example";

    # machine id in /etc/machine-id
    # required by systemd for consistent logs
    # passed as a boot parameter
    machineId = "$MACHINE_ID";

    # host id
    # required by ZFS
    hostId = "$HOST_ID";

  };

  # partition PARTUUIDS
  # get these from /dev/disk/by-partuuid/...
  partitions = {

    # root partition
    root = "2178694e-02";

  };

  # additional filesystem mounts
  filesystem = {

    # configure luks encrypted devices
    # each entry should have a uuid and keyfile
    luks = { };

    # configure mounts
    # directly map to fileSystems.* blocks
    mount = {

      # raw mounts, no additional options
      raw = { };

      # nosuid, nodev
      harden = { };

      # nosuid, nodev, noexec
      data = { };

      # nosuid, nodev, ro
      immutable = { };

      # nosuid, nodev, noexec, ro
      static = { };

    };

  };

  # usbguard allowed devices
  # all others are blocked
  usbs = [ ];

  # user information
  user = {

    # nsswitch username in /etc/passwd
    name = "example";

  };

  # localization and internationalization
  localization = {

    # Continent/City timezone
    timeZone = "UTC";

    # keyboard layout
    keyboard = "us";

    # locale
    locale = "en_US.UTF-8";

  };

  # networking options
  network = {

    # primary DNS resolver
    resolver = "10.0.0.3";

    # wpa_supplicant wireless networking
    wireless = {

      # enable wireless networking
      enable = false;

      # wireless NIC identifier
      interface = "wlp1s0";

      # wireless network ssid
      # WPA3-SAE password is stored using sops-nix
      ssid = "example";

      # wireless network gateway
      gateway = "10.0.0.1";

      # static IP address
      address = "10.0.0.2";

    };

    # wireguard vpn
    wireguard = {

      # enable wireguard
      enable = false;

      # wireguard address
      address = "10.20.0.2";

      # wireguard port
      port = 51820;

      # wireguard peers
      peers = [ ];

    };

    # hostapd AP and authentication server
    hostapd = {

      # enable hostapd
      enable = false;

      # hostapd wireless NIC identifier
      # hostapd and wireless can't use the same interface
      interface = "wlp1s1";

      # uplink interface
      # provides connectivity
      uplink = "eth0";

      # regulatory domain
      # as a country codeDNScrypt
      domain = "US";

      # ssid name
      # WPA3-SAE password is stored using sops-nix
      ssid = "example-lan";

      # address for gateway
      # prefix 24 will be used
      address = "192.168.0.1";

    };

    # optional wired networking
    # with DHCP
    wired = {

      # enable wired networking
      enable = false;

      # wired NIC identifier
      interface = "eth0";

    };

  };

  # service toggles
  services = {

    # dnscrypt-proxy DoH
    # loopback service
    dnscrypt = {
      enable = true;
    };

    # ssh server
    # lan service
    #
    # port is a port
    # trusted-keys is a list of ed25519 ssh public keys
    # allow is a private CIDR (LAN)
    ssh = {
      enable = false;
      port = 2222;
      trusted-keys = [ ];
      allow = "10.20.0.2/32";
    };

  };

  # additional feature toggles
  features = {

    # impermanence with tmpfs and bind mounts
    impermanence.enable = false;

  };

  # seed this machine remotely
  # trusted-keys is a list of nix public keys
  seed = {
    enable = false;
    trusted-keys = [ ];
  };

}
EOF

        echo 'before rebuilding, ensure that all variables are properly defined
invalid / inaccurate variables can lead to a broken system
bootstrap DOES NOT POPULATE VARIABLES with sane values, only examples

the following values have been populated from the installation environment
- device.machineId
- device.hostId'

    fi

    # set permissions for vars file
    sudo chmod 600 "$VARS"

#######
# SOPS
####### workstation, server, pi

elif [ "$VERB" == "sops" ]; then

    # allowed roles: workstation, server, pi
    if ! [[ "${ROLE:-}" =~ ^(workstation|server|pi)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi

    mkdir -p "$VARS_DIR"

    if [ -f "$SECRETS" ] && [[ "$ARG1" != "replace" ]]; then
        echo "Error: secrets.yaml already exists" >&2
        exit 1
    fi

    # check environment variables
    if [ -z "${SECRETS_HASHED_PASSWORD:-}" ]; then
        echo "SECRETS_HASHED_PASSWORD unset, using user input"

        while true; do
            echo "Set user account password"
            read -sp "Enter password  : " PASSWORD1
            echo
            read -sp "Confirm password: " PASSWORD2
            echo
            echo

            if [ "$PASSWORD1" == "$PASSWORD2" ]; then
                SECRETS_HASHED_PASSWORD=$(mkpasswd "$PASSWORD1" -m yescrypt)
                break
            else
                echo "Passwords do not match, try again"
            fi
        done
    fi

    if [ -z "${SECRETS_WIRELESS_PSK:-}" ]; then
        echo "SECRETS_WIRELESS_PSK unset, using user input"

        while true; do
            echo "Set wireless network password"
            read -sp "Enter password  : " PASSWORD1
            echo
            read -sp "Confirm password: " PASSWORD2
            echo
            echo

            if [ "$PASSWORD1" == "$PASSWORD2" ]; then
                SECRETS_WIRELESS_PSK="$PASSWORD1"
                break
            else
                echo "Passwords do not match, try again"
            fi
        done
    fi

    if [ -z "${SECRETS_SEED_KEY:-}" ]; then
        echo "SECRETS_SEED_KEY unset, generating new"
        SECRETS_SEED_KEY=$(nix key generate-secret --key-name seed)
    fi

    if [ -z "${SECRETS_WIREGUARD_KEY:-}" ]; then
        echo "SECRETS_WIREGUARD_KEY unset, generating new"
        SECRETS_WIREGUARD_KEY="$(wg genkey)"
    fi

    if [[ "${ROLE:-}" =~ ^(server)$ ]]; then

        if [ -z "${SECRETS_DUCKDNS_TOKEN:-}" ]; then
            echo "SECRETS_DUCKDNS_TOKEN unset, left empty"
            SECRETS_DUCKDNS_TOKEN=""
        fi

        if [ -z "${SECRETS_SEARXNG_KEY:-}" ]; then
            echo "SECRETS_SEARXNG_KEY unset, generating new"
            SECRETS_SEARXNG_KEY=$(head -c 64 /dev/urandom | sha256sum | cut -d ' ' -f1)
        fi

    fi

    # delete existing sops keys from gpg
    if [ -f "$SOPS_YAML" ]; then
        FINGERPRINT=$(yq '.keys[0]' "$SOPS_YAML")
        FINGERPRINT="${FINGERPRINT#\"}"
        FINGERPRINT="${FINGERPRINT%\"}"
        sudo GNUPGHOME="$SOPS_DIR" gpg --batch --yes --delete-secret-keys "$FINGERPRINT" || true
        sudo GNUPGHOME="$SOPS_DIR" gpg --batch --yes --delete-key "$FINGERPRINT" || true
    fi

    # delete old sops-nix directory if exists
    if [ -d "$SOPS_DIR" ]; then
        sudo rm -rf "$SOPS_DIR"
    fi
    sudo mkdir -p "$SOPS_DIR"

    # change ownership of sops-nix directory
    sudo chown root: "$SOPS_DIR"
    sudo chmod 700 "$SOPS_DIR"

    rm -rf /tmp/sops-nix

    # create new gpg key for sops-nix
    # save key fingerprint
    FINGERPRINT=$(nix run github:Mic92/sops-nix#sops-init-gpg-key -- --gpghome "/tmp/sops-nix" --keytype Curve25519 2>&1 | grep -oP '(?<=fingerprint:\s)\S+' | tail -n1)

    # ensure non-empty key
    if [ -z "$FINGERPRINT" ]; then
        echo "Error: Failed to generate a GPG key for sops-nix" >&2
        exit 1
    fi

    # move key to the sops-nix directory
    sudo cp -r /tmp/sops-nix/. "$SOPS_DIR/"

    # export the gpg key from sops-nix directory
    sudo GNUPGHOME="$SOPS_DIR" gpg --export --armor > /tmp/sops-nix-pub.asc
    sudo GNUPGHOME="$SOPS_DIR" gpg --export-secret-keys --armor > /tmp/sops-nix-priv.asc

    # securely purge keys
    shred /tmp/sops-nix-pub.asc -u
    shred /tmp/sops-nix-priv.asc -u
    find /tmp/sops-nix -type f -exec shred -u {} +
    rm -rf /tmp/sops-nix

    # create .sops.yaml configuration file
    cat > "$SOPS_YAML" <<EOF
keys:
  - &personal $FINGERPRINT
creation_rules:
  - path_regex: $(echo "$SECRETS" | sed "s|^$DIR/||")
    key_groups:
    - pgp:
      - *personal
  - path_regex: $TEMP_SECRETS
    key_groups:
    - pgp:
      - *personal
EOF

    #create the secrets file
    if [[ "${ROLE:-}" =~ ^(workstation|pi)$ ]]; then

        cat > "$TEMP_SECRETS" <<EOF
hashedPassword: $SECRETS_HASHED_PASSWORD

wireguard: $SECRETS_WIREGUARD_KEY

wireless: |
  psk=$SECRETS_WIRELESS_PSK

seed: $SECRETS_SEED_KEY
EOF

    elif [[ "${ROLE:-}" =~ ^(server)$ ]]; then

        cat > "$TEMP_SECRETS" <<EOF
hashedPassword: $SECRETS_HASHED_PASSWORD

wireguard: $SECRETS_WIREGUARD_KEY

wireless: |
  psk=$SECRETS_WIRELESS_PSK

seed: $SECRETS_SEED_KEY

duckdns: |
  DUCKDNS_TOKEN=$SECRETS_DUCKDNS_TOKEN

searxng: |
  SEARXNG_SECRET=$SECRETS_SEARXNG_KEY
EOF

    fi

    # open secrets file
    (
        cd "$DIR" || exit
        sudo GNUPGHOME="$SOPS_DIR" sops -e "$TEMP_SECRETS" > "$SECRETS"
        shred "$TEMP_SECRETS" -u
    )

    # set permissions for secrets file
    sudo chmod 600 "$SECRETS"

##########
# INSTALL
########## workstation, server

elif [ "$VERB" == "install" ]; then

    # allowed roles: workstation, server
    if ! [[ "${ROLE:-}" =~ ^(workstation|server)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi


    if ! [ "$MOUNT" == "/mnt" ]; then
        echo "Error: unexpected root mount $MOUNT"
        exit 1
    fi

    (
        cd "$DIR"
        git add .

        if [ "$NONFLAKE" = 1 ]; then
            sudo nixos-install --root "$MOUNT" --file "nonflake.nix" --attr "nixosConfigurations.machine-$ROLE-$ARCH" --no-root-passwd
        else
            sudo nixos-install --root "$MOUNT" --flake ".#machine-$ROLE-$ARCH" --no-root-passwd
        fi

        git reset -- vars/vars.nix vars/secrets.yaml .sops.yaml
    )

##########
# FINISH
######### workstation, server

elif [ "$VERB" == "finish" ]; then

    # allowed roles: workstation, server
    if ! [[ "${ROLE:-}" =~ ^(workstation|server)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi


    if ! [ "$MOUNT" == "/mnt" ]; then
        echo "Error: unexpected root mount $MOUNT"
        exit 1
    fi

    sudo umount -l /mnt/boot || true
    sudo umount -l /mnt/persist || true
    sudo umount -l /mnt/nix || true
    sudo umount -l /mnt || true
    sudo zpool export rpool -f

############# post-install
# LANZABOOTE
############# workstation, server

elif [ "$VERB" == "lanzaboote" ]; then

    # allowed roles: workstation, server
    if ! [[ "${ROLE:-}" =~ ^(workstation|server)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi

    if ! [ "$MOUNT" == "" ]; then
        echo "Error: unexpected root mount $MOUNT"
        exit 1
    fi

    if [ "$ARG1" == "create" ]; then
        nix shell nixpkgs#sbctl --command sudo sbctl create-keys
    fi

    if [ "$ARG1" == "enroll" ]; then
        nix shell nixpkgs#sbctl --command sudo sbctl enroll-keys --microsoft
    fi

############### post-install
# IMPERMANENCE
############### workstation, server, pi

elif [ "$VERB" == "impermanence" ]; then

    # allowed roles: workstation, server, pi
    if ! [[ "${ROLE:-}" =~ ^(workstation|server|pi)$ ]]; then
      echo "Error: unexpected role $ROLE" >&2
      exit 1
    fi

    if ! [ "$MOUNT" == "" ]; then
        echo "Error: unexpected root mount $MOUNT"
        exit 1
    fi

    if [ -n "$(sudo ls -A -- "$PERSIST_DIR_ROOT" 2>/dev/null)" ]; then
        echo "Error: $PERSIST_DIR_ROOT is not empty" >&2
        exit 1
    fi

    # ROOT
    sudo mkdir -p "$PERSIST_DIR_ROOT"

    # helper function
    persist_dirs() {
        local dest_base="$1"
        local src_root="$2"
        shift 2
        local sources=("$@")

        for src in "${sources[@]}"; do
            # strip leading slash
            local rel="${src#/}"

            # real source path
            local real_src="$src_root/$rel"

            # destination path
            local dest="$dest_base/$rel"

            # 1. create parent
            sudo mkdir -p "$(dirname "$dest")"

            # 2. copy if exists
            if [ -e "$real_src" ]; then
                sudo cp -a "$real_src" "$dest"
            fi

            # 3. ensure destination exists
            sudo mkdir -p "$dest"
        done
    }

    # set permissions
    sudo chown -R root: "$PERSIST_DIR_ROOT"

    # HOME
    sudo mkdir -p "$PERSIST_DIR_HOME"

    if [[ "${ROLE:-}" =~ ^(workstation)$ ]]; then

        # populate /persist/root/
        echo "Populating /persist/root/"
        persist_dirs "$PERSIST_DIR_ROOT" "$MOUNT$REAL_ROOT" \
            "/var/lib/nixos" \
            "/var/lib/systemd" \
            "/var/lib/sbctl" \
            "/var/lib/libvirt" \
            "/var/log" \
            "/etc/zfs" \
            "/etc/ssh"

        # populate /persist/root/home/
        echo "Populating /persist/root/home/"
        persist_dirs "$PERSIST_DIR_HOME" "$MOUNT$REAL_HOME" \
            "/Documents" \
            "/Downloads" \
            "/Pictures" \
            "/Projects" \
            "/.config/BraveSoftware/Brave-Browser" \
            "/.ssh" \
            "/.local/share/containers" \
            "/.local/state/nix"

    elif [[ "${ROLE:-}" =~ ^(server)$ ]]; then
        
        # populate /persist/root/
        echo "Populating /persist/root/"
        persist_dirs "$PERSIST_DIR_ROOT" "$MOUNT$REAL_ROOT"  \
            "/var/lib/nixos" \
            "/var/lib/systemd" \
            "/var/lib/sbctl" \
            "/var/lib/acme" \
            "/var/lib/bitwarden_rs" \
            "/var/lib/i2pd" \
            "/var/lib/qbt" \
            "/var/log" \
            "/etc/zfs" \
            "/etc/ssh" \
            "/srv/static" \
            "/srv/torrents"

    elif [[ "${ROLE:-}" =~ ^(pi)$ ]]; then
        
        # populate /persist/root/
        echo "Populating /persist/root/"
        persist_dirs "$PERSIST_DIR_ROOT" "$MOUNT$REAL_ROOT"  \
            "/var/lib/nixos" \
            "/var/lib/systemd" \
            "/var/log" \
            "/etc/zfs" \
            "/etc/ssh"

    fi

    # set permissions
    sudo chown -R "$USER": "$PERSIST_DIR_HOME"
    if [ -d "$PERSIST_DIR_HOME/.ssh" ]; then
        sudo chmod 700 "$PERSIST_DIR_HOME/.ssh"
        sudo find "$PERSIST_DIR_HOME/.ssh" -type f -exec chmod 600 {} +
        sudo find "$PERSIST_DIR_HOME/.ssh" -type d -exec chmod 700 {} +
    fi

fi

echo "Finished bootstrap task(s)"
