#!/usr/bin/env bash

set -euo pipefail

DIR="$__NIXOS_MOUNT$__NIXOS_GLOBALS_FLAKE"
ROLE="$__NIXOS_ROLE"
ARCH="$(nix eval --impure --raw --expr builtins.currentSystem)"
NONFLAKE="$__NIXOS_NONFLAKE"

(
    cd "$DIR"

    trap 'git reset -- vars/vars.nix vars/secrets.yaml .sops.yaml' EXIT

    git add .

    if [ "$NONFLAKE" = 1 ]; then
        nixos-rebuild build --file "nonflake.nix" --attr "nixosConfigurations.machine-$ROLE-$ARCH" --fallback
    else
        nixos-rebuild build --flake ".#machine-$ROLE-$ARCH" --fallback
    fi

)

