#!/usr/bin/env bash

set -euo pipefail

DIR="$__NIXOS_MOUNT$__NIXOS_GLOBALS_FLAKE"
ROLE="$__NIXOS_ROLE"

(
    cd "$DIR"

    trap 'git reset -- vars/vars.nix vars/secrets.yaml .sops.yaml' EXIT

    git add .

    run0 nixos-rebuild build --flake ".#machine-$ROLE" --fallback
)

