#!/usr/bin/env bash

set -euo pipefail

DIR="$__NIXOS_MOUNT$__NIXOS_GLOBALS_FLAKE"
ROLE="$__NIXOS_ROLE"

VARS_DIR="$DIR/vars"
VARS="$VARS_DIR/vars.nix"

SECRETS="$VARS_DIR/secrets.yaml"

case "$1" in
    vars)
        "${EDITOR:-vi}" "$VARS"
        ;;
    sops)
        sudo GNUPGHOME="$__NIXOS_GLOBALS_SOPS" sops "$SECRETS"
        ;;
    *)
    echo "Error: expected argument (vars/sops)" >&2
        exit 1
        ;;
esac
