#!/usr/bin/env bash

set -euo pipefail

: "${1:?Error: expected target host}"

rsync -avz --delete \
--exclude='vars/vars.nix' \
--exclude='vars/secrets.yaml' \
--exclude='.sops.yaml' \
--exclude='.git' \
--exclude='.local' \
"$__NIXOS_MOUNT$__NIXOS_GLOBALS_FLAKE/" \
$1:$__NIXOS_GLOBALS_FLAKE
