#!/usr/bin/env bash

set -euo pipefail

KEY="/run/secrets/seed"

HOST=${1:-}

if [ "$HOST" == "" ]; then
    
    run0 cat "$KEY" | nix key convert-secret-to-public

else

    role=$(ssh "$HOST" 'printf "%s" "$NIXOS_ROLE"')
    if [ -z "$role" ]; then
        echo "NIXOS_ROLE is not set on $HOST" >&2
        exit 1
    fi

    sourcedir=$(mktemp -d)
    workdir=$(mktemp -d)

    cleanup() {
        rm -rf "$sourcedir" "$workdir"
    }
    trap cleanup INT TERM EXIT

    rsync -avz --exclude=".git" "$HOST:/persist/nixos/" "$sourcedir"
    flake="$sourcedir#machine-$role"
    (
        cd "$workdir"
        nixos-rebuild build --flake "$flake"
        run0 nix store sign ./result -k "$KEY" --recursive
        nix copy --to "ssh://$HOST" ./result
    )

fi
