#!/usr/bin/env bash

set -e

if [ "$NIXOS_ROLE" != "laptop" ]; then
    echo "Error: unexpected role $NIXOS_ROLE" >&2
    exit 1
fi

if [ -z "$NIXOS_SCRIPTS_DIR" ]; then
    SCRIPTS="$NIXOS_DIR/scripts"
else
    SCRIPTS="$NIXOS_SCRIPTS_DIR"
fi

message=""

while [[ "$#" -gt 0 ]]; do
    case "$1" in
        -m|--message)
            shift
            message="$1"
            ;;
        *)
            echo "Error: unknown option: $1" >&2
            exit 1
            ;;
    esac
    shift
done

(
    cd $NIXOS_DIR
    $SCRIPTS/format
    $SCRIPTS/perms
    git add .
    GIT_PAGER=cat git diff HEAD -- ':!vars/vars.nix' ':!vars/secrets.yaml' ':!.sops.yaml'

    echo
    $SCRIPTS/digest

    read -p "continue? [Y/n]: " confirm

    confirm=${confirm:-Y}

    if [[ $confirm =~ ^[Yy]$ ]]; then

        sudo nixos-rebuild switch --flake .#$NIXOS_ROLE

        git reset -- vars/vars.nix vars/secrets.yaml .sops.yaml

        if [[ -n "$message" ]]; then
            git commit -m "$message" --allow-empty-message
        else
            git commit --allow-empty-message
        fi

	else
        echo "cancelled"
	fi
)
