#!/usr/bin/env bash

# Colors
bold=$'\e[1m'
underline=$'\e[4m'
dim=$'\e[2m'
reset=$'\e[0m'

# Foreground colors
blue=$'\e[34m'
cyan=$'\e[36m'
green=$'\e[32m'
yellow=$'\e[33m'
magenta=$'\e[35m'
red=$'\e[31m'
white=$'\e[97m'

cat <<EOF
${bold}${blue}NixOS Flake Helper${reset}
==================

${bold}${underline}Usage${reset}
  ${green}nixos${reset} [${cyan}command${reset}] [${yellow}args${reset}]

${dim}When run with no command, equivalent to:${reset}
  ${magenta}\$ nixos tree -I .git -I .local --filesfirst${reset}

${dim}When run with a command not mentioned below,
the command is dispatched to \$NIXOS_DIR.${reset}
  ${magenta}\$ nixos vi modules/common/firewall.nix${reset}

${bold}${underline}Commands${reset}

${bold}${yellow}  test${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos test${reset}
    Test the current configuration.
    Does not create a boot entry.

${bold}${yellow}  switch${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos switch${reset}
    Switch to the current configuration.
    Creates a boot entry.

${bold}${yellow}  commit${reset}
  ${dim}roles:${reset} laptop

    ${green}\$ nixos commit${reset}
    Switch to and commit the current configuration.
    Creates a boot entry and a Git commit.

${bold}${yellow}  update${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos update${reset}
    Update flake inputs in flake.lock.
    Equivalent to:
      ${magenta}\$ nixos nix flake update${reset}

${bold}${yellow}  format${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos format${reset}
    Format the flake using nixfmt.
    Equivalent to:
      ${magenta}\$ nixos find . -type f -name '*.nix' -exec nix fmt {} +${reset}

${bold}${yellow}  perms${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos perms${reset}
    Apply correct permissions to all files in the flake.

${bold}${yellow}  purge${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos purge${reset}
    Garbage collect old generations.
    Equivalent to:
      ${magenta}\$ sudo nix-collect-garbage --delete-old${reset}

${bold}${yellow}  repair${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos repair${reset}
    Attempt to repair the nix store.
    Equivalent to:
      ${magenta}\$ sudo nix-store --verify --check-contents --repair${reset}

${bold}${yellow}  edit <vars|sops>${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos edit vars${reset}
    Edit variables file

    ${green}\$ nixos edit sops${reset}
    Edit sops-nix secrets

${bold}${yellow}  serverpush <path>${reset}
  ${dim}roles:${reset} laptop

    ${green}\$ nixos serverpush /nixos${reset}
    Push the flake to server:/nixos

${bold}${yellow}  help${reset}
  ${dim}roles:${reset} laptop, server

    ${green}\$ nixos help${reset}
    Show this message and exit
EOF
