#! /usr/bin/env bash

DIR=$NIXOS_DIR
ROLE=$NIXOS_ROLE

VARS_DIR="$DIR/vars"
VARS="$VARS_DIR/vars.nix"

if [ "$ROLE" == "laptop" ]; then
    SOPS_DIR="/persist/sops-nix"
elif [ "$ROLE" == "server" ]; then
    SOPS_DIR="/var/lib/sops-nix"
else
    echo "Error: unexpected role $NIXOS_ROLE"
    exit 1
fi
SOPS_YAML="$DIR/.sops.yaml"
SECRETS="$VARS_DIR/secrets.yaml"
TEMP_SECRETS="/tmp/sops-nix-init.yaml"

PERSIST_DIR="/persist"
PERSIST_DIR_ROOT="$PERSIST_DIR/root"
PERSIST_DIR_HOME="$PERSIST_DIR_ROOT/home/$USER"

#################
# HWARDWARE INIT
#################

if [ "$1" == "hardware" ]; then

    if [ -f "modules/$ROLE/hardware-configuration.nix" ] && [[ "$2" != "replace" ]]; then
        echo "Error: hardware-configuration.nix already exists"
        exit 1
    fi

    sudo nixos-generate-config --dir /tmp/nixos

    echo "Warning: hardware configuration is now managed within the flake"
    exit 1

    if [ -f "/tmp/nixos/hardware-configuration.nix" ]; then
        if cp "/tmp/nixos/hardware-configuration.nix" "$DIR/modules/$ROLE/hardware-configuration.nix"; then
            echo "generated hardware-configuration.nix was moved to $DIR/modules/$ROLE/hardware-configuration.nix"
        else
            echo "Error: failed to copy hardware-configuration.nix" >&2
            exit 1
        fi
    fi

    sudo shred /tmp/nixos/configuration.nix
    sudo shred /tmp/nixos/hardware-configuration.nix
    sudo rm -rf /tmp/nixos

############
# VARS INIT
############

elif [ "$1" == "vars" ]; then

    mkdir -p $VARS_DIR

    if [ -f "$VARS" ] && [[ "$2" != "replace" ]]; then
        echo "Error: vars.nix already exists"
        exit 1
    else
	cp $VARS "/tmp/vars.nix"
        rm $VARS
    fi

    if [ "$ROLE" == "laptop" ]; then

        # check environment variables for vars
        if [ -z "$VARS_DEVICE_HOSTNAME" ]; then
            VARS_DEVICE_HOSTNAME=$(uname -n)
        fi

        if [ -z "$VARS_DEVICE_MACHINEID" ]; then
            VARS_DEVICE_MACHINEID=$(cat /etc/machine-id)
        fi

        if [ -z "$VARS_DEVICE_HOSTID" ]; then
            VARS_DEVICE_HOSTID=$(head -c 8 /etc/machine-id)
        fi

        if [ -z "$VARS_DEVICE_BOOT" ]; then
            echo "Warning: VARS_DEVICE_BOOT is unset"
            VARS_DEVICE_BOOT=""
        fi

        if [ -z "$VARS_DEVICE_SWAP" ]; then
            echo "Warning: VARS_DEVICE_SWAP is unset"
            VARS_DEVICE_SWAP=""
        fi

        if [ -z "$VARS_DEVICE_ROOT" ]; then
            echo "Warning: VARS_DEVICE_ROOT is unset"
            VARS_DEVICE_ROOT=""
        fi

	if [ -z "$VARS_DEVICE_SECUREBOOT_ENABLE" ]; then
	    VARS_DEVICE_SECUREBOOT_ENABLE="false"
	fi

	if [ -z "$VARS_DEVICE_IMPERMANENCE_ENABLE" ]; then
	    VARS_DEVICE_IMPERMANENCE_ENABLE="false"
	fi

	if [ -z "$VARS_DEVICE_PLYMOUTH_ENABLE" ]; then
	    VARS_DEVICE_PLYMOUTH_ENABLE="false"
	fi

	if [ -z "$VARS_DEVICE_AUTOCPUFREQ_ENABLE" ]; then
	    VARS_DEVICE_AUTOCPUFREQ_ENABLE="true"
	fi

	if [ -z "$VARS_DEVICE_POWERTOP_ENABLE" ]; then
	    VARS_DEVICE_POWERTOP_ENABLE="false"
	fi

	if [ -z "$VARS_DEVICE_TLP_ENABLE" ]; then
	    VARS_DEVICE_TLP_ENABLE="false"
	fi
	
        if [ -z "$VARS_USER_NAME" ]; then
            VARS_USER_NAME=$USER
        fi

        if [ -z "$VARS_USER_EMAIL" ]; then
            echo "Warning: VARS_USER_EMAIL is unset"
            VARS_USER_EMAIL=""
        fi

        if [ -z "$VARS_USER_GITHUB_KEYFILE" ]; then
            VARS_USER_GITHUB_KEYFILE="id_ed25519_github"
        fi

        if [ -z "$VARS_I18N_TIMEZONE" ]; then
            VARS_I18N_TIMEZONE=$(timedatectl show --property=Timezone --value)
        fi

        if [ -z "$VARS_I18N_KEYBOARD" ]; then
            VARS_I18N_KEYBOARD="us"
        fi

        if [ -z "$VARS_I18N_LOCALE" ]; then
            VARS_I18N_LOCALE="en_US.UTF-8"
        fi

        if [ -z "$VARS_NETWORK_INTERFACE" ]; then
            VARS_NETWORK_INTERFACE="wlp1s0"
        fi

        if [ -z "$VARS_NETWORK_SSID" ]; then
            echo "Warning: VARS_NETWORK_SSID is unset"
            VARS_NETWORK_SSID=""
        fi

        if [ -z "$VARS_NETWORK_GATEWAY" ]; then
            VARS_NETWORK_GATEWAY="192.168.0.1"
        fi

        if [ -z "$VARS_NETWORK_IP" ]; then
            echo "Warning: VARS_NETWORK_IP is unset"
            VARS_NETWORK_IP=""
        fi

        if [ -z "$VARS_NETWORK_SERVER_ENABLE" ]; then
            VARS_NETWORK_SERVER_ENABLE="true"
        fi

        if [ -z "$VARS_NETWORK_SERVER_IP" ]; then
            VARS_NETWORK_SERVER_IP=""
        fi

        if [ -z "$VARS_NETWORK_SERVER_DOMAIN" ]; then
            VARS_NETWORK_SERVER_DOMAIN=""
        fi

        if [ -z "$VARS_NETWORK_SERVER_SSH_PORT" ]; then
            VARS_NETWORK_SERVER_SSH_PORT="22"
        fi

        if [ -z "$VARS_NETWORK_SERVER_SSH_KEYFILE" ]; then
            VARS_NETWORK_SERVER_SSH_KEYFILE="id_ed25519_server"
        fi

        if [ -z "$VARS_NETWORK_SERVER_I2P_PORT" ]; then
            VARS_NETWORK_SERVER_I2P_PORT="4444"
        fi

        if [ -z "$VARS_OUTPUTS_LAPTOP" ]; then
            VARS_OUTPUTS_LAPTOP="eDP-1"
        fi

        if [ -z "$VARS_OUTPUTS_MONITOR" ]; then
            VARS_OUTPUTS_MONITOR="HDMI-A-1"
        fi

	if [ -z "$VARS_OUTPUTS_WALLPAPER" ]; then
            VARS_OUTPUTS_WALLPAPER="mario"
        fi

        # create vars file
        cat > $VARS <<EOF
{
  # use this file to declare variables
  # this file will be stored in the world-readable /nix/store
  # for any sensitive data, use sops-nix instead
  # this file and ./secrets.yaml are not tracked by git

  ######################################
  # NIXOS CONFIGURATION FLAKE VARIABLES
  ######################################

  # directory where nixos configuration is stored
  nixosDirectory = "$NIXOS_DIR";

  # configuration role
  nixosRole = "laptop";

  ###################
  # DEVICE VARIABLES
  ###################

  # /etc/hostname
  device.hostName = "$VARS_DEVICE_HOSTNAME";

  # /etc/machine-id
  # passed as a boot parameter
  # do not change for consistent journald logs
  device.machineId = "$VARS_DEVICE_MACHINEID";

  # required for zfs
  device.hostId = "$VARS_DEVICE_HOSTID";

  # partition partuuids
  # find them from /dev/disk/by-partuuid/...
  # assumes a specific configuration
  # see ../docs/laptop-setup.md
  device.boot = "$VARS_DEVICE_BOOT";
  device.swap = "$VARS_DEVICE_SWAP";
  device.root = "$VARS_DEVICE_ROOT";

  # luks: encrypted luks devices
  # example usage:
  # device.luks = [
  #   {
  #       name = "ht02";
  #       uuid = "3f74d2e3-5a67-4b86-b2c3-842f39e45b7a";
  #       id = "usb-Samsung_192939485710293857281029-0:0";
  #       keyfile = "/root/keys/ht02";
  #       mount = "/mnt/ht02";
  #       fs = "xfs";
  #       hdparm = false;
  #   }
  # ];
  device.luks = [ ];

  # secure boot: boot signed software
  # provided by the lanzaboote project
  # read docs/laptop-setup.md before enabling
  device.secureboot.enable = $VARS_DEVICE_SECUREBOOT_ENABLE;

  # impermanence: erase your darlings
  # using zfs snapshots and bind mounts
  # read docs/laptop-setup.md before enabling
  # requires: secureboot
  device.impermanence.enable = $VARS_DEVICE_IMPERMANENCE_ENABLE;

  # plymouth: boot splash screen
  device.plymouth.enable = $VARS_DEVICE_PLYMOUTH_ENABLE;

  # auto-cpufreq: optimize cpu speed & power
  device.auto-cpufreq.enable = $VARS_DEVICE_AUTOCPUFREQ_ENABLE;

  # powertop: power management tool
  device.powertop.enable = $VARS_DEVICE_POWERTOP_ENABLE;

  # tlp: optimize battery life
  device.tlp.enable = $VARS_DEVICE_TLP_ENABLE;

  #########################
  # USER ACCOUNT VARIABLES
  #########################

  # your username
  user.name = "$VARS_USER_NAME";

  # your email
  user.email = "$VARS_USER_EMAIL";

  # github ssh keyfile
  user.github.keyfile = "$VARS_USER_GITHUB_KEYFILE";

  #################
  # I18N VARIABLES
  #################

  # continent/city format timezone
  i18n.timeZone = "$VARS_I18N_TIMEZONE";

  # keyboard layout
  i18n.keyboard = "$VARS_I18N_KEYBOARD";

  # locale
  i18n.locale = "$VARS_I18N_LOCALE";

  #######################
  # NETWORKING VARIABLES
  #######################

  # wireless interface
  network.interface = "$VARS_NETWORK_INTERFACE";

  # wireless network ssid
  network.ssid = "$VARS_NETWORK_SSID";

  # network gateway
  network.gateway = "$VARS_NETWORK_GATEWAY";

  # static local device ip
  network.ip = "$VARS_NETWORK_IP";

  # whether to use server features or not
  network.server.enable = $VARS_NETWORK_SERVER_ENABLE;

  # static local home server ip address
  network.server.ip = "$VARS_NETWORK_SERVER_IP";

  # server domain
  network.server.domain = "$VARS_NETWORK_SERVER_DOMAIN";

  # server ssh port
  network.server.ssh.port = $VARS_NETWORK_SERVER_SSH_PORT;

  # server ssh keyfile
  network.server.ssh.keyfile = "$VARS_NETWORK_SERVER_SSH_KEYFILE";

  # server i2p HTTP proxy port
  network.server.i2p.port = $VARS_NETWORK_SERVER_I2P_PORT;

  #############################
  # OUTPUT (DISPLAY) VARIABLES
  #############################

  # builtin laptop screen identifier (usually eDP-1)
  outputs.laptop = "$VARS_OUTPUTS_LAPTOP";

  # external monitor screen identifier (usually HDMI-A-1)
  outputs.monitor = "$VARS_OUTPUTS_MONITOR";

  # wallpaper
  outputs.wallpaper = "$VARS_OUTPUTS_WALLPAPER";
}
EOF

    elif [ "$ROLE" == "server" ]; then

        # check environment variables for vars
        if [ -z "$VARS_DEVICE_HOSTNAME" ]; then
            VARS_DEVICE_HOSTNAME=$(uname -n)
        fi

        if [ -z "$VARS_DEVICE_MACHINEID" ]; then
            VARS_DEVICE_MACHINEID=$(cat /etc/machine-id)
        fi

        if [ -z "$VARS_DEVICE_ROOT" ]; then
            echo "Warning: VARS_DEVICE_ROOT is unset"
            VARS_DEVICE_ROOT=""
        fi

        if [ -z "$VARS_USER_NAME" ]; then
            VARS_USER_NAME=$USER
        fi

        if [ -z "$VARS_USER_EMAIL" ]; then
            echo "Warning: VARS_USER_EMAIL is unset"
            VARS_USER_EMAIL=""
        fi

        if [ -z "$VARS_I18N_TIMEZONE" ]; then
            VARS_I18N_TIMEZONE=$(timedatectl show --property=Timezone --value)
        fi

        if [ -z "$VARS_I18N_KEYBOARD" ]; then
            VARS_I18N_KEYBOARD="us"
        fi

        if [ -z "$VARS_I18N_LOCALE" ]; then
            VARS_I18N_LOCALE="en_US.UTF-8"
        fi

        if [ -z "$VARS_NETWORK_INTERFACE" ]; then
            VARS_NETWORK_INTERFACE="wlan0"
        fi

        if [ -z "$VARS_NETWORK_SSID" ]; then
            echo "Warning: VARS_NETWORK_SSID is unset"
            VARS_NETWORK_SSID=""
        fi

        if [ -z "$VARS_NETWORK_GATEWAY" ]; then
            VARS_NETWORK_GATEWAY="192.168.0.1"
        fi

        if [ -z "$VARS_NETWORK_RANGE" ]; then
            VARS_NETWORK_RANGE="192.168.0.0/24"
        fi

        if [ -z "$VARS_NETWORK_IP" ]; then
            echo "Warning: VARS_NETWORK_IP is unset"
            VARS_NETWORK_IP=""
        fi

        if [ -z "$VARS_NETWORK_DUCKDNS_DOMAIN" ]; then
            VARS_NETWORK_DUCKDNS_DOMAIN="$(uname -n)-server.duckdns.org"
        fi

        if [ -z "$VARS_NETWORK_SSH_PORT" ]; then
            VARS_NETWORK_SSH_PORT="22"
        fi

        if [ -z "$VARS_NETWORK_SSH_KEY" ]; then
            echo "Warning: VARS_NETWORK_SSH_KEY is unset"
            VARS_NETWORK_SSH_KEY=""
        fi

	if [ -z "$VARS_NETWORK_UNBOUND_ENABLE" ]; then
	    VARS_NETWORK_UNBOUND_ENABLE="false"
	fi

	if [ -z "$VARS_NETWORK_NGINX_ENABLE" ]; then
	    VARS_NETWORK_NGINX_ENABLE="false"
	fi

	if [ -z "$VARS_NETWORK_SEARXNG_ENABLE" ]; then
	    VARS_NETWORK_SEARXNG_ENABLE="false"
	fi

	if [ -z "$VARS_NETWORK_VAULTWARDEN_ENABLE" ]; then
	    VARS_NETWORK_VAULTWARDEN_ENABLE="false"
	fi

        if [ -z "$VARS_NETWORK_VAULTWARDEN_DATA" ]; then
            VARS_NETWORK_VAULTWARDEN_DATA="/var/lib/bitwarden_rs"
        fi

        if [ -z "$VARS_NETWORK_VAULTWARDEN_PORT" ]; then
            VARS_NETWORK_VAULTWARDEN_PORT="8222"
        fi

	if [ -z "$VARS_NETWORK_I2PD_ENABLE" ]; then
	    VARS_NETWORK_I2PD_ENABLE="false"
	fi

        if [ -z "$VARS_NETWORK_I2PD_SAM_PORT" ]; then
            VARS_NETWORK_I2PD_SAM_PORT="7656"
        fi

        if [ -z "$VARS_NETWORK_I2PD_HTTP_PROXY_PORT" ]; then
            VARS_NETWORK_I2PD_HTTP_PROXY_PORT="4444"
        fi

        if [ -z "$VARS_NETWORK_I2PD_SOCKS_PROXY_PORT" ]; then
            VARS_NETWORK_I2PD_SOCKS_PROXY_PORT="4447"
        fi

        if [ -z "$VARS_NETWORK_I2PD_WEBCONSOLE_PORT" ]; then
            VARS_NETWORK_I2PD_WEBCONSOLE_PORT="7070"
        fi

	if [ -z "$VARS_NETWORK_QBT_ENABLE" ]; then
	    VARS_NETWORK_QBT_ENABLE="false"
	fi

        if [ -z "$VARS_NETWORK_QBT_DATA" ]; then
            VARS_NETWORK_QBT_DATA="/var/lib/qbt/data"
        fi

        if [ -z "$VARS_NETWORK_QBT_PORT" ]; then
            VARS_NETWORK_QBT_PORT="8080"
        fi

	if [ -z "$VARS_NETWORK_JELLYFIN_ENABLE" ]; then
	    VARS_NETWORK_JELLYFIN_ENABLE="false"
	fi

        if [ -z "$VARS_NETWORK_JELLYFIN_PORT" ]; then
            VARS_NETWORK_JELLYFIN_PORT="8096"
        fi

        # create vars file
        cat > $VARS <<EOF
{
  # use this file to declare variables
  # this file will be stored in the world-readable /nix/store
  # for any sensitive data, use sops-nix instead
  # this file and ./secrets.yaml are not tracked by git

  ######################################
  # NIXOS CONFIGURATION FLAKE VARIABLES
  ######################################

  # directory where nixos configuration is stored
  nixosDirectory = "$NIXOS_DIR";

  # configuration role
  nixosRole = "server";

  ###################
  # DEVICE VARIABLES
  ###################

  # /etc/hostname
  device.hostName = "$VARS_DEVICE_HOSTNAME";

  # /etc/machine-id
  # passed as a boot parameter
  # do not change for consistent journald logs
  device.machineId = "$VARS_DEVICE_MACHINEID";

  # partition partuuids
  # find them from /dev/disk/by-partuuid/...
  # assumes a specific configuration
  # see ../docs/server-setup.md
  device.root = "$VARS_DEVICE_ROOT";

  # luks: encrypted luks devices
  # example usage:
  # device.luks = [
  #   {
  #       name = "ht02";
  #       uuid = "3f74d2e3-5a67-4b86-b2c3-842f39e45b7a";
  #       id = "usb-Samsung_192939485710293857281029-0:0";
  #       keyfile = "/root/keys/ht02";
  #       mount = "/mnt/ht02";
  #       fs = "xfs";
  #       hdparm = false;
  #   }
  # ];
  device.luks = [ ];

  #########################
  # USER ACCOUNT VARIABLES
  #########################

  # your username
  user.name = "$VARS_USER_NAME";

  # your email
  user.email = "$VARS_USER_EMAIL";

  #################
  # I18N VARIABLES
  #################

  # continent/city format timezone
  i18n.timeZone = "$VARS_I18N_TIMEZONE";

  # keyboard layout
  i18n.keyboard = "$VARS_I18N_KEYBOARD";

  # locale
  i18n.locale = "$VARS_I18N_LOCALE";

  #######################
  # NETWORKING VARIABLES
  #######################

  # wireless interface
  network.interface = "$VARS_NETWORK_INTERFACE";

  # wireless network ssid
  network.ssid = "$VARS_NETWORK_SSID";

  # network gateway
  network.gateway = "$VARS_NETWORK_GATEWAY";

  # local ip range
  network.range = "$VARS_NETWORK_RANGE";

  # static local device ip
  network.ip = "$VARS_NETWORK_IP";

  # duckdns domain
  network.duckdns.domain = "$VARS_NETWORK_DUCKDNS_DOMAIN";

  # ssh (LAN) port
  network.ssh.port = $VARS_NETWORK_SSH_PORT;

  # ssh keys
  network.ssh.keys = [ "$VARS_NETWORK_SSH_KEY" ];

  # unbound: validating recursive dns server
  network.unbound.enable = $VARS_NETWORK_UNBOUND_ENABLE;

  # nginx: web server
  network.nginx.enable = $VARS_NETWORK_NGINX_ENABLE;

  # searxng: metasearch engine
  # requires: nginx
  network.searxng.enable = $VARS_NETWORK_SEARXNG_ENABLE;

  # vaultwarden: password manager
  # requires: nginx
  network.vaultwarden.enable = $VARS_NETWORK_VAULTWARDEN_ENABLE;

  # vaultwarden data directory
  network.vaultwarden.data = "$VARS_NETWORK_VAULTWARDEN_DATA";

  # vaultwarden (loopback) port
  network.vaultwarden.port = $VARS_NETWORK_VAULTWARDEN_PORT;

  # i2pd: invisible internet protocol daemon
  # requires: nginx
  network.i2pd.enable = $VARS_NETWORK_I2PD_ENABLE;

  # i2pd SAM (loopback) port
  network.i2pd.sam.port = $VARS_NETWORK_I2PD_SAM_PORT;

  # i2pd HTTP proxy (LAN) port
  network.i2pd.httpProxy.port = $VARS_NETWORK_I2PD_HTTP_PROXY_PORT;

  # i2pd SOCKS proxy (loopback) port
  network.i2pd.socksProxy.port = $VARS_NETWORK_I2PD_SOCKS_PROXY_PORT;

  # i2pd webconsole (loopback) port
  network.i2pd.webconsole.port = $VARS_NETWORK_I2PD_WEBCONSOLE_PORT;

  # qbittorrent: bittorrent client
  # requires: i2pd, nginx
  network.qbt.enable = $VARS_NETWORK_QBT_ENABLE;

  # qbittorrent data directory
  network.qbt.data = "$VARS_NETWORK_QBT_DATA";

  # qbittorrent (loopback) port
  network.qbt.port = $VARS_NETWORK_QBT_PORT;

  # jellyfin: media server
  # requires: nginx
  network.jellyfin.enable = $VARS_NETWORK_JELLYFIN_ENABLE;

  # jellyfin (loopback) port
  network.jellyfin.port = $VARS_NETWORK_JELLYFIN_PORT;
}
EOF

    fi

    # set permissions for vars file
    sudo chmod 600 $VARS

#############
# SOPS INIT
#############

elif [ "$1" == "sops" ]; then

    mkdir -p $VARS_DIR

    if [ -f "$SECRETS" ] && [[ "$2" != "replace" ]]; then
        echo "Error: secrets.yaml already exists"
        exit 1
    else
	cp $SECRETS "/tmp/secrets.yaml"
        rm $SECRETS
    fi

    # check environment variables
    if [ -z "$SECRETS_HASHED_PASSWORD" ]; then
        echo "Set user account password"

        while true; do
            read -sp "Enter password: " PASSWORD1
            echo
            read -sp "Confirm password: " PASSWORD2
            echo

            if [ "$PASSWORD1" == "$PASSWORD2" ]; then
                SECRETS_HASHED_PASSWORD=$(mkpasswd "$PASSWORD1" -m yescrypt)
                break
            else
                echo "Passwords do not match, try again"
            fi
        done
    fi

    if [ -z "$SECRETS_PSK" ]; then
        echo "Set wireless network password"

        while true; do
            read -sp "Enter password: " PASSWORD1
            echo
            read -sp "Confirm password: " PASSWORD2
            echo

            if [ "$PASSWORD1" == "$PASSWORD2" ]; then
                SECRETS_PSK="$PASSWORD1"
                break
            else
                echo "Passwords do not match, try again"
            fi
        done
    fi

    if [ "$ROLE" == "server" ]; then

        if [ -z "$SECRETS_DUCKDNS_TOKEN" ]; then
            echo "Warning: SECRETS_DUCKDNS_TOKEN is unset"
            SECRETS_DUCKDNS_TOKEN=""
        fi

        if [ -z "$SECRETS_SEARXNG_KEY" ]; then
            SECRETS_SEARXNG_KEY=$(head -c 64 /dev/urandom | sha256sum | cut -d ' ' -f1)
        fi

    fi

    # delete existing sops keys from gpg
    if [ -f "$SOPS_YAML" ]; then
        FINGERPRINT=$(nix shell nixpkgs#yq --command yq '.keys[0]' $SOPS_YAML)
        FINGERPRINT="${FINGERPRINT#\"}"
        FINGERPRINT="${FINGERPRINT%\"}"
        nix shell nixpkgs#gnupg --command sudo GNUPGHOME=$SOPS_DIR gpg --batch --yes --delete-secret-keys $FINGERPRINT
        nix shell nixpkgs#gnupg --command sudo GNUPGHOME=$SOPS_DIR gpg --batch --yes --delete-key $FINGERPRINT
    fi

    # delete old sops-nix directory if exists
    if [ -d $SOPS_DIR ]; then
        sudo rm -rf $SOPS_DIR
    fi
    sudo mkdir $SOPS_DIR

    # change ownership of sops-nix directory
    sudo chown root: $SOPS_DIR
    sudo chmod 700 $SOPS_DIR

    # create new gpg key for sops-nix
    # save key fingerprint
    FINGERPRINT=$(yes n | nix run github:Mic92/sops-nix#sops-init-gpg-key -- --gpghome "/tmp/sops-nix" --keytype Curve25519 2>&1 | grep -oP '(?<=fingerprint:\s)\S+')

    # ensure non-empty key
    if [ -z "$FINGERPRINT" ]; then
        echo "Error: Failed to generate a GPG key for sops-nix" >&2
        exit 1
    fi

    # move key to the sops-nix directory
    sudo cp -r /tmp/sops-nix/** $SOPS_DIR

    # export the gpg key from sops-nix directory
    nix shell nixpkgs#gnupg --command sudo GNUPGHOME=$SOPS_DIR gpg --export --armor > /tmp/sops-nix-pub.asc
    nix shell nixpkgs#gnupg --command sudo GNUPGHOME=$SOPS_DIR gpg --export-secret-keys --armor > /tmp/sops-nix-priv.asc

    # securely purge keys
    shred /tmp/sops-nix-pub.asc -u
    shred /tmp/sops-nix-priv.asc -u
    find /tmp/sops-nix -type f -exec shred -u {} +
    rm -rf /tmp/sops-nix

    # create .sops.yaml configuration file
    cat > $SOPS_YAML <<EOF
keys:
  - &personal $FINGERPRINT
creation_rules:
  - path_regex: $(echo $SECRETS | sed "s|^$DIR/||")
    key_groups:
    - pgp:
      - *personal
  - path_regex: $TEMP_SECRETS
    key_groups:
    - pgp:
      - *personal
EOF

    #create the secrets file
    if [ "$ROLE" == "laptop" ]; then

        cat > $TEMP_SECRETS <<EOF
hashedPassword: $SECRETS_HASHED_PASSWORD
network: |
  psk=$SECRETS_PSK
EOF

    elif [ "$ROLE" == "server" ]; then

        cat > $TEMP_SECRETS <<EOF
hashedPassword: $SECRETS_HASHED_PASSWORD
network: |
  psk=$SECRETS_PSK
duckdns: |
  DUCKDNS_TOKEN=$SECRETS_DUCKDNS_TOKEN
searxng: |
  SEARXNG_SECRET=$SECRETS_SEARXNG_KEY
EOF

    fi

    # open secrets file
    (
        cd $DIR || exit
        nix shell nixpkgs#sops nixpkgs#gnupg --command sudo GNUPGHOME=$SOPS_DIR sops -e $TEMP_SECRETS > $SECRETS
        shred $TEMP_SECRETS -u
    )

    # set permissions for secrets file
    sudo chmod 600 $SECRETS


#############
# LANZABOOTE
#############

elif [ "$1" == "lanzaboote" ]; then

    if ! [ "$ROLE" == "laptop" ]; then
        echo "Error: unexpected role $NIXOS_ROLE"
        exit 1
    fi

    if [ "$2" == "create" ]; then
        nix shell nixpkgs#sbctl --command sudo sbctl create-keys
    fi

    if [ "$2" == "enroll" ]; then
        nix shell nixpkgs#sbctl --command sudo sbctl enroll-keys --microsoft
    fi

###############
# IMPERMANENCE
###############

elif [ "$1" == "impermanence" ]; then

    if ! [ "$ROLE" == "laptop" ]; then
        echo "Error: unexpected role $NIXOS_ROLE"
        exit 1
    fi

    if [ ! -d "$PERSIST_DIR" ]; then
        echo "Error: $PERSIST_DIR doesn't exist"
        exit 1
    fi

    if [ -d "$PERSIST_DIR_ROOT" ]; then
        echo "$PERSIST_DIR_ROOT already exists"
        exit 0
    fi

    if [ -d "$PERSIST_DIR_HOME" ]; then
        echo "$PERSIST_DIR_HOME already exists"
        exit 0
    fi

    # ROOT
    sudo mkdir $PERSIST_DIR_ROOT

    # zpool.cache
    sudo mkdir -p $PERSIST_DIR_ROOT/etc/zfs
    sudo cp --preserve=mode,ownership,timestamps /etc/zfs/zpool.cache $PERSIST_DIR_ROOT/etc/zfs/zpool.cache

    # /var/lib/nixos
    sudo mkdir -p $PERSIST_DIR_ROOT/var/lib
    sudo cp -r --preserve=mode,ownership,timestamps /var/lib/nixos $PERSIST_DIR_ROOT/var/lib/nixos

    # /var/lib/systemd
    sudo mkdir -p $PERSIST_DIR_ROOT/var/lib
    sudo cp -r --preserve=mode,ownership,timestamps /var/lib/systemd $PERSIST_DIR_ROOT/var/lib/systemd

    # /var/lib/sbctl
    sudo mkdir -p $PERSIST_DIR_ROOT/var/lib
    sudo cp -r --preserve=mode,ownership,timestamps /var/lib/sbctl $PERSIST_DIR_ROOT/var/lib/sbctl

    # /var/log
    sudo mkdir -p $PERSIST_DIR_ROOT/var
    sudo cp -r --preserve=mode,ownership,timestamps /var/log $PERSIST_DIR_ROOT/var/log

    sudo chown -R root: $PERSIST_DIR_ROOT

    # HOME
    sudo mkdir -p $PERSIST_DIR_HOME

    # Documents
    sudo mkdir $PERSIST_DIR_HOME/Documents
    sudo cp -r --preserve=mode,ownership,timestamps $HOME/Documents $PERSIST_DIR_HOME/Documents

    # Downloads
    sudo mkdir $PERSIST_DIR_HOME/Downloads
    sudo cp -r --preserve=mode,ownership,timestamps $HOME/Downloads $PERSIST_DIR_HOME/Downloads

    # Pictures
    sudo mkdir $PERSIST_DIR_HOME/Pictures
    sudo cp -r --preserve=mode,ownership,timestamps $HOME/Pictures $PERSIST_DIR_HOME/Pictures

    # Projects
    sudo mkdir $PERSIST_DIR_HOME/Projects
    sudo cp -r --preserve=mode,ownership,timestamps $HOME/Projects $PERSIST_DIR_HOME/Projects

    # Brave Browser
    sudo mkdir -p $PERSIST_DIR_HOME/.config/BraveSoftware/Brave-Browser
    sudo cp -r --preserve=mode,ownership,timestamps $HOME/.config/BraveSoftware/Brave-Browser $PERSIST_DIR_HOME/.config/BraveSoftware/Brave-Browser

    # SSH
    sudo mkdir $PERSIST_DIR_HOME/.ssh
    sudo cp -r --preserve=mode,ownership,timestamps $HOME/.ssh $PERSIST_DIR_HOME/.ssh

    sudo chown -R $USER: $PERSIST_DIR_ROOT/home

    sudo chmod 700 $PERSIST_DIR_HOME/.ssh

fi
