#!/usr/bin/env bash

start_time=$(date +%s)

if [ -z "$NIXOS_DIR" ]; then
    echo "Error: NIXOS_DIR is not set." >&2
    exit 1
fi

if [ -z "$NIXOS_ROLE" ]; then
    echo "Error: NIXOS_ROLE is not set." >&2
    exit 1
fi

if ! [[ "$NIXOS_ROLE" =~ ^(server|laptop)$ ]]; then
  echo "Error: unexpected role $NIXOS_ROLE" >&2
  exit 1
fi

set -e

DIR="$NIXOS_DIR"
ROLE="$NIXOS_ROLE"

if [ -z "$NIXOS_SCRIPTS_DIR" ]; then
    SCRIPTS="$DIR/scripts"
else
    SCRIPTS="$NIXOS_SCRIPTS_DIR"
fi

# print directory tree when run with no arguments
if [ $# -eq 0 ]; then
        cmd=("tree" "$DIR" "--filesfirst")

# run scripts
elif [ -f "$SCRIPTS/$1" ]; then
	cmd=("$SCRIPTS/$1" "${@:2}")

# run commands
else
	cmd=("$@")
fi

if [[ "$1" =~ ^(commit|format|init|perms|purge|switch|test|update)$ ]]; then
    # ensure there is only one instance running
    LOCKFILE="/tmp/nixos-script.lock"

    # open lockfile on fd 9
    exec 9>"$LOCKFILE" || {
        echo "Error: cannot open lockfile $LOCKFILE" >&2
        exit 1
    }

    # acquire exclusive non-blocking lock
    if ! flock -n 9; then
        echo "Error: another instance of the script is running." >&2
        exit 1
    fi

    # lock is automatically released when fd 9 is closed on exit
fi

(
    if [ "$1" != "init" ]; then
    	cd $DIR || exit 1
    fi
	"${cmd[@]}"
)

end_time=$(date +%s)
end_date=$(date "+%Y-%m-%d %H:%M:%S")
duration=$((end_time - start_time))
echo >&2
echo "[nixos] finshed in ${duration}s" >&2
