#!/usr/bin/env bash

set -e

find "$NIXOS_DIR" -path "$NIXOS_DIR/.git" -prune -o -exec chown "$USER": {} +

find "$NIXOS_DIR" -path "$NIXOS_DIR/.git" -prune -o -type d -exec chmod 700 {} \;
find "$NIXOS_DIR" -path "$NIXOS_DIR/.git" -prune -o -type f -exec chmod 600 {} \;

chmod 700 -R "$NIXOS_DIR/scripts"
