#! /usr/bin/env bash

if [ -z "$1" ]; then
    echo "Error: expected target directory"
    exit 1
fi

if [ "$NIXOS_ROLE" == "laptop" ]; then
    rsync -avz --delete \
    --exclude='modules/laptop/hardware-configuration.nix' \
    --exclude='modules/server/hardware-configuration.nix' \
    --exclude='vars/vars.nix' \
    --exclude='vars/secrets.yaml' \
    --exclude='.sops.yaml' \
    --exclude='.git' \
    --exclude='.local' \
    $NIXOS_DIR/ \
    server:$1/
else
    echo "Error: unexpected role $NIXOS_ROLE"
    exit 1
fi