#!/usr/bin/env bash

if [ -z "$NIXOS_SCRIPTS_DIR" ]; then
    SCRIPTS="$NIXOS_DIR/scripts"
else
    SCRIPTS="$NIXOS_SCRIPTS_DIR"
fi

set -e

(
    cd $NIXOS_DIR
    $SCRIPTS/format
    git add .
    if [ "$NIXOS_ROLE" == "laptop" ]; then
        GIT_PAGER=cat git diff HEAD -- ':!vars/vars.nix' ':!vars/secrets.yaml' ':!.sops.yaml'
    fi

    echo
    vars_hash=$(sha256sum "$NIXOS_DIR/vars/vars.nix" | awk '{print $1}')
    vars_r=$((16#${vars_hash:0:2}))
    vars_g=$((16#${vars_hash:2:2}))
    vars_b=$((16#${vars_hash:4:2}))
    sops_hash=$(sha256sum "$NIXOS_DIR/vars/secrets.yaml" | awk '{print $1}')
    sops_r=$((16#${sops_hash:0:2}))
    sops_g=$((16#${sops_hash:2:2}))
    sops_b=$((16#${sops_hash:4:2}))
    echo -e "\033[1m\033[38;2;${vars_r};${vars_g};${vars_b}mvars:\033[0m $vars_hash $(stat -c %y "$NIXOS_DIR/vars/vars.nix")"
    echo -e "\033[1m\033[38;2;${sops_r};${sops_g};${sops_b}msops:\033[0m $sops_hash $(stat -c %y "$NIXOS_DIR/vars/secrets.yaml")"

    read -p "switch? [Y/n]: " confirm

    confirm=${confirm:-Y}

    if [[ $confirm =~ ^[Yy]$ ]]; then

        sudo nixos-rebuild switch --flake .#$NIXOS_ROLE

        git reset -- vars/vars.nix vars/secrets.yaml .sops.yaml

	else
            echo "cancelled"
	fi
)
