#!/usr/bin/env bash

if [ -z "$NIXOS_SCRIPTS_DIR" ]; then
    SCRIPTS="$NIXOS_DIR/scripts"
else
    SCRIPTS="$NIXOS_SCRIPTS_DIR"
fi

set -e

(
    cd $NIXOS_DIR
    $SCRIPTS/format
    git add .
    if [ "$NIXOS_ROLE" == "laptop" ]; then
        GIT_PAGER=cat git diff HEAD -- ':!vars/vars.nix' ':!vars/secrets.yaml' ':!.sops.yaml'
    fi

    echo
    $SCRIPTS/digest

    read -p "continue? [Y/n]: " confirm

    confirm=${confirm:-Y}

    if [[ $confirm =~ ^[Yy]$ ]]; then

        sudo nixos-rebuild switch --flake .#$NIXOS_ROLE

        git reset -- vars/vars.nix vars/secrets.yaml .sops.yaml

	else
            echo "cancelled"
	fi
)
