#! /usr/bin/env bash

if [ -z "$NIXOS_DIR" ]; then
    echo "Error: NIXOS_DIR is not set." >&2
    exit 1
fi

if [ -z "$NIXOS_ROLE" ]; then
    echo "Error: NIXOS_ROLE is not set." >&2
    exit 1
fi

(
	cd $NIXOS_DIR
	nix flake update
)
