name: Build SD-Card Image

on:
  push:
    paths:
      - 'modules/images/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Generate timestamp
        id: ts
        run: echo "ts=$(date +%s)" >> $GITHUB_OUTPUT

      # -----------------------------------------------------
      # Build SDCard Image
      # -----------------------------------------------------
      - name: Build sdcard image
        run: |
          nix build github:sotormd/nixos#nixosConfigurations.imageSDCard.config.system.build.sdImage

          SD_SRC=$(echo result/sd-image/*.img.zst)
          SD_DST="nixos-sdcard-${{ steps.ts.outputs.ts }}.img.zst"
          cp "$SD_SRC" "$SD_DST"

      # -----------------------------------------------------
      # Upload Artifacts
      # -----------------------------------------------------
      - name: Upload sdcard image
        uses: actions/upload-artifact@v4
        with:
          name: nixos-sdcard
          path: nixos-sdcard-${{ steps.ts.outputs.ts }}.img.zst
