name: Build MATE ISO

on:
  push:
    paths:
      - 'modules/images/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build MATE ISO
        run: |
          nix run nixpkgs#nixos-generators -- \
            --format iso \
            --flake .#image-mate \
            -o mate-image

      - name: Upload MATE ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos-mate
          path: mate-image/iso/*.iso
