name: Build GNOME ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build GNOME ISO
        run: |
          nix run nixpkgs#nixos-generators -- \
            --format iso \
            --flake .#image-gnome \
            -o gnome-image

      - name: Upload GNOME ISO
        uses: actions/upload-artifact@v4
        with:
          name: nixos-gnome
          path: gnome-image/iso/*.iso
