name: Check

on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Ensure variables and secrets are not present
        run: |
          if [ -f "./.sops.yaml" ]; then
            exit 1
          fi
          if [ -d "./vars/" ]; then
            exit 1
          fi

      - name: Generate stub vars for checks
        run: |
          mkdir -p vars
          cp .github/stubvars.nix vars/vars.nix
          touch vars/secrets.yaml

      - name: Stage changes
        run: git add .

      - name: Check
        run: nix flake check --all-systems
