name: Evaluate Image - SD

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: SD image evaluation
        run: nix eval .#nixosConfigurations.image-sd-aarch64-linux.config.system.build.toplevel --json

