name: Evaluate Image - GNOME

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: GNOME image evaluation
        run: nix eval .#nixosConfigurations.image-gnome-x86_64-linux.config.system.build.toplevel --json

