name: Evaluate SD Image

on:
  push:
  pull_request:

jobs:
  nix-eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: SD image evaluation
        run: nix eval .#nixosConfigurations.image-sd.config.system.build.toplevel

