name: (Non-Flake) Evaluate Machine - Server

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Generate stub vars for checks
        run: |
          mkdir -p vars
          cp .github/stubvars.nix vars/vars.nix
          touch vars/secrets.yaml

      - name: Stage changes
        run: git add .

      - name: Server evaluation
        run: nix eval -f nonflake.nix nixosConfigurations.machine-server-x86_64-linux.config.system.build.toplevel --json
