name: (Non-Flake) Evaluate Image - Minimal

on:
  push:
    branches: [master]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Minimal image evaluation
        run: nix eval -f nonflake.nix nixosConfigurations.image-minimal-x86_64-linux.config.system.build.toplevel --json
